name: investbot

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: postgres -c track_commit_timestamp=on

  airflow:
    image: apache/airflow:3.1.0
    restart: unless-stopped
    depends_on: 
      - db
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@db:5432/airflow
      - PYTHONPATH=/opt/airflow/app
      - _PIP_ADDITIONAL_REQUIREMENTS= ${_PIP_ADDITIONAL_REQUIREMENTS:-}
      - PG_HOST=investbot-postgres-1
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DB=$PG_DB
      - AIRFLOW__STANDALONE_USER=${_AIRFLOW_WWW_USER_CREATE:-airflow}
      - AIRFLOW__STANDALONE_PASSWORD=${_AIRFLOW_WWW_PASSWORD:-airflow}
    ports:
      - 8080:8080
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/app
      - ./requirements.txt:/opt/airflow/requirements.txt
    user: "${AIRFLOW_UID:-50000}:0"
    command: airflow standalone

volumes:
  db_data:
